config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'race_results/index'
  get 'race_results/show'
  get 'race_results/new'
  get 'race_results/create'
  get 'race_results/edit'
  get 'race_results/update'
  get 'race_results/destroy'
  get 'races/index'
  get 'races/show'
  get 'races/new'
  get 'races/create'
  get 'races/edit'
  get 'races/update'
  get 'races/destroy'
  get 'events/index'
  get 'events/show'
  get 'events/new'
  get 'events/create'
  get 'events/edit'
  get 'events/update'
  get 'events/destroy'
  get 'organizations/index'
  get 'organizations/show'
  get 'organizations/new'
  get 'organizations/create'
  get 'organizations/edit'
  get 'organizations/update'
  get 'organizations/destroy'
  get 'runners/index'
  get 'runners/show'
  get 'runners/new'
  get 'runners/create'
  get 'runners/edit'
  get 'runners/update'
  get 'runners/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization
  has_many :races
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
  has_many :runners
  has_many :events
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :event
  has_many :race_results
  has_many :runners, through: :race_results
end

app/models/race_result.rb
class RaceResult < ApplicationRecord
  belongs_to :runner
  belongs_to :race
  
  validates :time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :position, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
end

app/models/runner.rb
class Runner < ApplicationRecord
  belongs_to :user
  belongs_to :organization, optional: true
  has_many :race_results
  has_many :races, through: :race_results
end

app/models/user.rb
class User < ApplicationRecord
  has_one :runner
  has_one :organization
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private

  def event_params
    params.require(:event).permit(:attribute1, :attribute2, :attribute3)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.find(params[:id])
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to @organization, notice: 'Organization was successfully created.'
    else
      render :new
    end
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])
    if @organization.update(organization_params)
      redirect_to @organization, notice: 'Organization was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy
    redirect_to organizations_url, notice: 'Organization was successfully destroyed.'
  end

  private

  def organization_params
    params.require(:organization).permit(:attribute1, :attribute2, :attribute3)
  end
end

app/controllers/race_results_controller.rb
class RaceResultsController < ApplicationController
  def index
    @race_results = RaceResult.all
  end

  def show
    @race_result = RaceResult.find(params[:id])
  end

  def new
    @race_result = RaceResult.new
  end

  def create
    @race_result = RaceResult.new(race_result_params)
    if @race_result.save
      redirect_to @race_result, notice: 'Race Result was successfully created.'
    else
      render :new
    end
  end

  def edit
    @race_result = RaceResult.find(params[:id])
  end

  def update
    @race_result = RaceResult.find(params[:id])
    if @race_result.update(race_result_params)
      redirect_to @race_result, notice: 'Race Result was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @race_result = RaceResult.find(params[:id])
    @race_result.destroy
    redirect_to race_results_url, notice: 'Race Result was successfully destroyed.'
  end

  private

  def runner_params
    params.require(:race_result).permit(:attribute1, :attribute2, :attribute3)
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def index
    @races = Race.all
  end

  def show
    @race = Race.find(params[:id])
  end

  def new
    @race = Race.new
  end

  def create
    @race = Race.new(race_params)
    if @race.save
      redirect_to @race, notice: 'Race was successfully created.'
    else
      render :new
    end
  end

  def edit
    @race = Race.find(params[:id])
  end

  def update
    @race = Race.find(params[:id])
    if @race.update(race_params)
      redirect_to @race, notice: 'Race was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @race = Race.find(params[:id])
    @race.destroy
    redirect_to races_url, notice: 'Race was successfully destroyed.'
  end

  private

  def race_params
    params.require(:race).permit(:attribute1, :attribute2, :attribute3)
  end
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  def index
    @runners = Runner.all
  end

  def show
    @runner = Runner.find(params[:id])
  end

  def new
    @runner = Runner.new
  end

  def create
    @runner = Runner.new(runner_params)
    if @runner.save
      redirect_to @runner, notice: 'Runner was successfully created.'
    else
      render :new
    end
  end

  def edit
    @runner = Runner.find(params[:id])
  end

  def update
    @runner = Runner.find(params[:id])
    if @runner.update(runner_params)
      redirect_to @runner, notice: 'Runner was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @runner = Runner.find(params[:id])
    @runner.destroy
    redirect_to runners_url, notice: 'Runner was successfully destroyed.'
  end

  private

  def runner_params
    params.require(:runner).permit(:attribute1, :attribute2, :attribute3)
  end
end

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Mi Aplicación</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <h1>Bienvenido a Mi Aplicación</h1>
    <nav>
      <%= link_to 'Inicio', root_path %>
      <%= link_to 'Eventos', events_path %>
      <%= link_to 'Corredores', runners_path %>
    </nav>
  </header>

  <main>
    <h2>¡Hola, mundo!</h2>
    <p>Este es el contenido de tu vista principal.</p>
    <div id="react-component"></div>
  </main>

  <footer>
    <p>&copy; <%= Time.now.year %> Mi Aplicación</p>
  </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>YourAppName</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/runners/_form.hmtl.erb
<%= form_with(model: @runner, local: true) do |form| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>
  
      <ul>
        <% @runner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :attribute1 %>
    <%= form.text_field :attribute1 %>
  </div>
  
  <div class="field">
    <%= form.label :attribute2 %>
    <%= form.text_field :attribute2 %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  

app/views/runners/edit.html.erb
<h1>New Runner</h1>

<%= render 'form' %>

<%= link_to 'Back', runners_path %>

app/views/runners/index.html.erb
<h1>Runners</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @runners.each do |runner| %>
      <tr>
        <td><%= runner.id %></td>
        <td><%= runner.attribute1 %></td>
        <td><%= runner.attribute2 %></td>
        <td><%= link_to 'Show', runner %></td>
        <td><%= link_to 'Edit', edit_runner_path(runner) %></td>
        <td><%= link_to 'Destroy', runner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Runner', new_runner_path %>

app/views/runners/new.html.erb
<h1>New Runner</h1>

<%= render 'form' %>

<%= link_to 'Back', runners_path %>

app/views/runners/show.html.erb
<h1><%= @runner.attribute1 %></h1>

<p>
  <strong>ID:</strong>
  <%= @runner.id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @runner.attribute2 %>
</p>

<%= link_to 'Edit', edit_runner_path(@runner) %> |
<%= link_to 'Back', runners_path %>